import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { Rocket, Plus, Trophy } from 'lucide-react';

export default function SprintMode() {
  const { language } = useAuth();
  const lang = language || 'uz';
  const [sprints, setSprints] = useState(() => { const s = localStorage.getItem('flowly-sprints'); return s ? JSON.parse(s) : []; });
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title: '', target: '', days: 7 });
  const today = new Date().toISOString().split('T')[0];
  useEffect(() => { localStorage.setItem('flowly-sprints', JSON.stringify(sprints)); }, [sprints]);
  const handleAdd = () => { if (!form.title || !form.target) return; setSprints([...sprints, { id: Date.now(), ...form, startDate: today, endDate: new Date(Date.now() + form.days * 86400000).toISOString().split('T')[0], completedDays: [] }]); setForm({ title: '', target: '', days: 7 }); setShowForm(false); };
  const toggleDay = (id, d) => { setSprints(sprints.map(s => s.id === id ? { ...s, completedDays: s.completedDays.includes(d) ? s.completedDays.filter(x => x !== d) : [...s.completedDays, d] } : s)); };
  const getDay = (s) => Math.min(Math.floor((new Date(today) - new Date(s.startDate)) / 86400000) + 1, s.days);
  const L = { title: lang==='ru'?'Спринт-челлендж':lang==='en'?'Sprint Challenge':'Sprint Challenge', desc: lang==='ru'?'Краткосрочные вызовы':lang==='en'?'Short-term challenges':'Qisqa muddatli challenge', add: lang==='ru'?'Новый':lang==='en'?'New':'Yangi', name: lang==='ru'?'Цель':lang==='en'?'Goal':'Maqsad', target: lang==='ru'?'Ежедневное действие':lang==='en'?'Daily action':'Kunlik ish', days: lang==='ru'?'дн':lang==='en'?'days':'kun', empty: lang==='ru'?'Нет спринтов':lang==='en'?'No sprints':'Sprint yo\'q', done: lang==='ru'?'Завершён!':lang==='en'?'Done!':'Tugallandi!' };
  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>🚀 {L.title}</h1><p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{L.desc}</p></div><button className="btn-primary flex items-center gap-2" onClick={() => setShowForm(!showForm)}><Plus size={18} />{L.add}</button></div>
      {showForm && (<div className="card animate-in space-y-3" style={{ borderColor: 'var(--accent)' }}><input type="text" placeholder={L.name} value={form.title} onChange={e => setForm({...form, title: e.target.value})} className="w-full px-4 py-2.5 rounded-xl border outline-none focus:ring-2 focus:ring-blue-500" style={{ background: 'var(--bg-secondary)', borderColor: 'var(--border)', color: 'var(--text-primary)' }} /><input type="text" placeholder={L.target} value={form.target} onChange={e => setForm({...form, target: e.target.value})} className="w-full px-4 py-2.5 rounded-xl border outline-none focus:ring-2 focus:ring-blue-500" style={{ background: 'var(--bg-secondary)', borderColor: 'var(--border)', color: 'var(--text-primary)' }} /><div className="flex gap-2">{[3,5,7,14,21,30].map(d => (<button key={d} onClick={() => setForm({...form, days: d})} className={`px-3 py-2 rounded-xl text-sm font-bold transition-all ${form.days===d?'bg-blue-500 text-white':''}`} style={form.days!==d?{background:'var(--bg-secondary)',color:'var(--text-secondary)'}:{}}>{d} {L.days}</button>))}</div><button className="btn-primary w-full" onClick={handleAdd}>{L.add}</button></div>)}
      {sprints.length === 0 && !showForm && <div className="card text-center py-12"><Rocket size={48} className="text-blue-300 mx-auto mb-4" /><p style={{ color: 'var(--text-secondary)' }}>{L.empty}</p></div>}
      <div className="space-y-4">{sprints.map(sprint => { const day = getDay(sprint); const complete = sprint.completedDays.length >= sprint.days; const progress = Math.round((sprint.completedDays.length / sprint.days) * 100); return (<div key={sprint.id} className={`card ${complete ? 'ring-2 ring-green-500' : ''}`}><div className="flex items-center gap-3 mb-3"><div className={`w-10 h-10 rounded-2xl flex items-center justify-center ${complete ? 'bg-green-100 dark:bg-green-900/20' : 'bg-blue-50 dark:bg-blue-900/20'}`}>{complete ? <Trophy size={20} className="text-green-500" /> : <Rocket size={20} className="text-blue-500" />}</div><div className="flex-1"><h3 className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{sprint.title}</h3><p className="text-xs" style={{ color: 'var(--text-secondary)' }}>{sprint.target} • {sprint.days} {L.days}</p></div><span className={`text-xs font-bold ${complete?'text-green-500':''}`} style={!complete?{color:'var(--accent)'}:{}}>{progress}%</span></div><div className="w-full h-2 rounded-full mb-3" style={{ background: 'var(--bg-secondary)' }}><div className={`h-2 rounded-full transition-all ${complete?'bg-green-500':'bg-gradient-to-r from-blue-500 to-purple-500'}`} style={{ width: `${progress}%` }} /></div><div className="flex flex-wrap gap-1.5">{Array.from({length: sprint.days}, (_,i) => { const d = i+1; const done = sprint.completedDays.includes(d); const cur = d===day; return (<button key={d} onClick={() => toggleDay(sprint.id, d)} className={`w-7 h-7 rounded-lg text-[9px] font-bold flex items-center justify-center transition-all ${done?'bg-green-500 text-white':cur?'ring-2 ring-blue-500':''}`} style={!done&&!cur?{background:'var(--bg-secondary)',color:'var(--text-secondary)'}:{}}>{done?'✓':d}</button>); })}</div>{complete && <p className="text-center mt-3 text-sm font-bold text-green-500">🎉 {L.done}</p>}</div>); })}</div>
    </div>
  );
}
