import { createContext, useContext, useState, useEffect } from 'react';

const AuthContext = createContext();

const defaultUsers = [
  {
    id: 'admin',
    email: 'admin@flowly.uz',
    phone: '+998930057077',
    password: 'admin123',
    login: 'yaxyobek',
    name: 'Yaxyobek',
    surname: 'Nematillaev',
    age: 18,
    address: 'Andijon, O\'zbekiston',
    avatar: null,
    role: 'admin',
    plan: 'vip',
    planExpiry: null,
    points: 500,
    trialEndsAt: null,
    joinedAt: '2026-01-01',
    referralCode: 'YAXY2026',
    referredBy: null,
    friends: [],
    language: 'uz',
    loginStreak: 7,
    lastLoginDate: '2026-06-02',
    totalLogins: 120,
  }
];

// ===== FULL TRANSLATIONS =====
const translations = {
  uz: {
    // Auth
    welcome: "Xush kelibsiz",
    login: "Kirish",
    signup: "Ro'yxatdan o'tish",
    email: "Email yoki telefon",
    password: "Parol",
    phone: "Telefon raqam",
    code: "Tasdiqlash kodi",
    sendCode: "Kod yuborish",
    verifyCode: "Kodni tasdiqlash",
    resetPassword: "Parolni tiklash",
    orLoginWith: "Yoki kirish",
    google: "Google",
    icloud: "iCloud",
    phoneLogin: "Telefon",
    forgotPassword: "Parolni unutdingizmi?",
    noAccount: "Akkauntingiz yo'qmi?",
    haveAccount: "Akkauntingiz bormi?",
    name: "Ism",
    surname: "Familya",
    age: "Yosh",
    address: "Manzil",
    createAccount: "Akkaunt yaratish",
    enterCode: "Kodni kiriting",
    enterPhone: "Telefon raqamni kiriting",
    requiredFields: "Email va parol majburiy",
    back: "Orqaga",
    slogan: "Plan. Act. Achieve.",
    description: "Hayotingizni boshqaring — kunlik, haftalik, oylik va yillik rejalar bilan",
    // Navigation
    dashboard: "Asosiy",
    dailyPlanner: "Kunlik reja",
    weeklyPlanner: "Haftalik reja",
    monthlyPlanner: "Oylik reja",
    yearlyGoals: "Yillik maqsadlar",
    habitTracker: "Odatlar",
    notes: "Yozuvlar",
    analytics: "Statistika",
    achievements: "Yutuqlar",
    location: "Xarita",
    certificates: "Sertifikatlar",
    friends: "Do'stlar",
    premium: "Premium",
    settings: "Sozlamalar",
    profile: "Profil",
    help: "Yordam",
    adminPanel: "Admin Panel",
    crmErp: "CRM / ERP",
    // Common
    search: "Qidirish...",
    save: "Saqlash",
    cancel: "Bekor qilish",
    delete: "O'chirish",
    edit: "Tahrirlash",
    add: "Qo'shish",
    close: "Yopish",
    yes: "Ha",
    no: "Yo'q",
    loading: "Yuklanmoqda...",
    noData: "Ma'lumot yo'q",
    today: "Bugun",
    tomorrow: "Ertaga",
    yesterday: "Kecha",
    week: "Hafta",
    month: "Oy",
    year: "Yil",
    all: "Barchasi",
    completed: "Bajarildi",
    notCompleted: "Bajarilmadi",
    progress: "Progress",
    streak: "Streak",
    points: "Ball",
    logout: "Chiqish",
    switchAccount: "Akkaunt almashtirish",
    // Dashboard
    welcomeUser: "Xush kelibsiz",
    lifeScore: "Life Activity Score",
    todayTasks: "Bugungi vazifalar",
    upcomingEvents: "Yaqinlashayotgan voqealar",
    activeStreaks: "Faol Streak'lar",
    aiRecommendations: "AI Tavsiyalari",
    excellent: "Ajoyib!",
    average: "O'rtacha",
    needsImprovement: "Yaxshilash kerak",
    dailyTasks: "Kunlik vazifalar",
    weeklyTasks: "Haftalik vazifalar",
    maxStreak: "Max Streak",
    // Daily Planner
    newTask: "Yangi vazifa",
    taskName: "Vazifa nomi",
    time: "Vaqt",
    priority: "Prioritet",
    high: "Yuqori",
    medium: "O'rtacha",
    low: "Past",
    category: "Kategoriya",
    personal: "Shaxsiy",
    education: "Ta'lim",
    health: "Sog'liq",
    work: "Ish",
    finance: "Moliya",
    todayProgress: "Bugungi progress",
    addTask: "Vazifa qo'shish",
    // Weekly
    monday: "Dushanba",
    tuesday: "Seshanba",
    wednesday: "Chorshanba",
    thursday: "Payshanba",
    friday: "Juma",
    saturday: "Shanba",
    sunday: "Yakshanba",
    noTasks: "Vazifa yo'q",
    // Monthly
    addEvent: "Voqea qo'shish",
    eventName: "Voqea nomi",
    eventType: "Turi",
    birthday: "Tug'ilgan kun",
    exam: "Imtihon",
    meeting: "Uchrashuv",
    event: "Tadbir",
    locationLabel: "Lokatsiya",
    noEventsDay: "Bu kunda voqealar yo'q",
    // Goals
    newGoal: "Yangi maqsad",
    goalName: "Maqsad nomi",
    deadline: "Deadline",
    steps: "Bosqichlar",
    stepsHint: "Har bir qator — yangi bosqich",
    overallProgress: "Umumiy progress",
    // Habits
    newHabit: "Yangi odat",
    habitName: "Odat nomi",
    dailyTarget: "Kunlik maqsad",
    selectIcon: "Icon tanlang",
    customIcon: "O'z emoji kiriting",
    completedToday: "Bugun bajarildi",
    longestStreak: "Eng uzun streak",
    todayPercent: "Bugungi foiz",
    monthlyView: "Oylik ko'rinish",
    // Notes
    newNote: "Yangi yozuv",
    noteTitle: "Sarlavha",
    noteContent: "Matn...",
    general: "Umumiy",
    business: "Biznes",
    tech: "Texnologiya",
    // Analytics
    lifeScoreLabel: "Life Score",
    completedLabel: "Bajarilgan",
    failedLabel: "Bajarilmagan",
    totalStreak: "Jami streak",
    goalsProgress: "Maqsadlar progressi",
    weeklyTasksChart: "Haftalik vazifalar",
    monthlyLifeScore: "Oylik Life Score",
    taskStatus: "Vazifalar holati",
    failedTasksWarning: "Bajarilmagan vazifalar",
    habitStreaks: "Odat streak'lari",
    // Achievements
    unlockedAchievements: "Ochilgan yutuqlar",
    medals: "Medallar",
    topStreaks: "Top Streak'lar",
    achievedLabel: "Bajarildi",
    // Certificates
    certificatesTitle: "Sertifikatlar va Yutuqlar",
    certificatesDesc: "Diplomlar, mukofotlar, erishgan natijalatingiz",
    certName: "Nomi",
    certIssuer: "Kim bergan",
    certDesc: "Tavsif",
    certLink: "Havola (ixtiyoriy)",
    certFile: "Fayl yuklash (rasm/PDF)",
    // Friends
    friendsTitle: "Do'stlar & Referral",
    friendsDesc: "Do'stlarni taklif qiling va bonuslar oling",
    invited: "Taklif qilganlar",
    pointsEarned: "Ball olindi",
    referralCode: "Referral kod",
    inviteLink: "Taklif havolasi",
    copy: "Nusxalash",
    copied: "Nusxalandi!",
    rewardLevels: "Mukofotlar darajasi",
    friendsList: "Do'stlar ro'yxati",
    noFriendsYet: "Hali do'stlar taklif qilinmagan",
    inviteFriends: "ta do'st taklif qiling",
    reward: "Mukofot",
    achieved: "Olingan",
    // Premium
    premiumTitle: "Premium",
    premiumDesc: "Flowly'ning to'liq quvvatidan foydalaning",
    trialBanner: "7 kunlik VIP sinov davri",
    trialEnds: "Tugash sanasi",
    allFeaturesOpen: "Barcha Premium funksiyalar sizga ochiq!",
    referralDiscount: "Do'stlar chegirmasi!",
    currentPlan: "Joriy reja",
    selectPlan: "Tanlash",
    popular: "Mashhur",
    pointsSystem: "Ball tizimi",
    pointsDesc: "Ballar yordamida Premium reja sotib olish mumkin",
    dayActivity: "kun faollik",
    consecutive: "kun ketma-ket",
    fullWeek: "to'liq hafta",
    // Settings
    settingsTitle: "Sozlamalar",
    appearance: "Ko'rinish",
    darkTheme: "Qora tema",
    lightTheme: "Oq tema",
    languageLabel: "Til",
    notificationsLabel: "Bildirishnomalar",
    pushNotifs: "Push bildirishnomalar",
    emailNotifs: "Email xabarnomalar",
    reminders: "Eslatmalar",
    weeklyReport: "Haftalik hisobot",
    account: "Akkaunt",
    viewProfile: "Profilni ko'rish",
    // Profile
    profileTitle: "Profil",
    personalInfo: "Shaxsiy ma'lumotlar",
    accountInfo: "Akkaunt ma'lumotlari",
    plan: "Plan",
    memberSince: "A'zo bo'lgan",
    // Help
    helpTitle: "Yordam & Qo'llab-quvvatlash",
    helpDesc: "Savollaringiz bormi? Biz yordam beramiz!",
    faq: "Ko'p so'raladigan savollar",
    liveChat: "Jonli chat",
    contactUs: "Biz bilan bog'lanish",
    telegram: "Telegram",
    phoneSupport: "Telefon",
    // Location
    locationTitle: "Location & Map",
    locationDesc: "Geolokatsiya, xarita va yo'l ko'rsatish",
    addPlace: "Joy qo'shish",
    searchPlace: "Joy qidirish...",
    placeName: "Joy nomi",
    placeAddress: "Manzil",
    openInMaps: "Xaritada",
    getDirections: "Yo'l",
    eventsLocation: "Voqealar joylashuvi",
    // Admin
    adminTitle: "Admin Panel",
    adminDesc: "Foydalanuvchilarni boshqarish",
    totalUsers: "Jami foydalanuvchilar",
    premiumUsers: "Premium",
    freeUsers: "Bepul",
    admins: "Adminlar",
    searchUser: "Foydalanuvchi qidirish...",
    noAccess: "Ruxsat yo'q",
    adminOnly: "Bu bo'lim faqat admin uchun ochiq",
    // Notifications
    notifications: "Bildirishnomalar",
    clearAll: "Tozalash",
    noNotifications: "Bildirishnomalar yo'q",
    minutesBefore: "daqiqa oldin",
    taskReminder: "Vazifa eslatmasi",
  },
  ru: {
    welcome: "Добро пожаловать",
    login: "Войти",
    signup: "Регистрация",
    email: "Email или телефон",
    password: "Пароль",
    phone: "Номер телефона",
    code: "Код подтверждения",
    sendCode: "Отправить код",
    verifyCode: "Подтвердить",
    resetPassword: "Сбросить пароль",
    orLoginWith: "Или войти через",
    google: "Google",
    icloud: "iCloud",
    phoneLogin: "Телефон",
    forgotPassword: "Забыли пароль?",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    name: "Имя",
    surname: "Фамилия",
    age: "Возраст",
    address: "Адрес",
    createAccount: "Создать аккаунт",
    enterCode: "Введите код",
    enterPhone: "Введите номер телефона",
    requiredFields: "Email и пароль обязательны",
    back: "Назад",
    slogan: "Plan. Act. Achieve.",
    description: "Управляйте жизнью — ежедневные, еженедельные и годовые планы",
    dashboard: "Главная",
    dailyPlanner: "День",
    weeklyPlanner: "Неделя",
    monthlyPlanner: "Месяц",
    yearlyGoals: "Цели года",
    habitTracker: "Привычки",
    notes: "Заметки",
    analytics: "Аналитика",
    achievements: "Достижения",
    location: "Карта",
    certificates: "Сертификаты",
    friends: "Друзья",
    premium: "Премиум",
    settings: "Настройки",
    profile: "Профиль",
    help: "Помощь",
    adminPanel: "Админ панель",
    crmErp: "CRM / ERP",
    search: "Поиск...",
    save: "Сохранить",
    cancel: "Отмена",
    delete: "Удалить",
    edit: "Редактировать",
    add: "Добавить",
    close: "Закрыть",
    yes: "Да",
    no: "Нет",
    loading: "Загрузка...",
    noData: "Нет данных",
    today: "Сегодня",
    tomorrow: "Завтра",
    yesterday: "Вчера",
    week: "Неделя",
    month: "Месяц",
    year: "Год",
    all: "Все",
    completed: "Выполнено",
    notCompleted: "Не выполнено",
    progress: "Прогресс",
    streak: "Серия",
    points: "Баллы",
    logout: "Выйти",
    switchAccount: "Сменить аккаунт",
    welcomeUser: "Добро пожаловать",
    lifeScore: "Life Activity Score",
    todayTasks: "Задачи на сегодня",
    upcomingEvents: "Ближайшие события",
    activeStreaks: "Активные серии",
    aiRecommendations: "Рекомендации ИИ",
    excellent: "Отлично!",
    average: "Средне",
    needsImprovement: "Нужно улучшить",
    dailyTasks: "Ежедневные задачи",
    weeklyTasks: "Еженедельные задачи",
    maxStreak: "Макс серия",
    newTask: "Новая задача",
    taskName: "Название задачи",
    time: "Время",
    priority: "Приоритет",
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",
    category: "Категория",
    personal: "Личное",
    education: "Учёба",
    health: "Здоровье",
    work: "Работа",
    finance: "Финансы",
    todayProgress: "Прогресс за сегодня",
    addTask: "Добавить задачу",
    monday: "Понедельник",
    tuesday: "Вторник",
    wednesday: "Среда",
    thursday: "Четверг",
    friday: "Пятница",
    saturday: "Суббота",
    sunday: "Воскресенье",
    noTasks: "Нет задач",
    addEvent: "Добавить событие",
    eventName: "Название события",
    eventType: "Тип",
    birthday: "День рождения",
    exam: "Экзамен",
    meeting: "Встреча",
    event: "Событие",
    locationLabel: "Локация",
    noEventsDay: "В этот день нет событий",
    newGoal: "Новая цель",
    goalName: "Название цели",
    deadline: "Дедлайн",
    steps: "Этапы",
    stepsHint: "Каждая строка — новый этап",
    overallProgress: "Общий прогресс",
    newHabit: "Новая привычка",
    habitName: "Название привычки",
    dailyTarget: "Дневная цель",
    selectIcon: "Выберите иконку",
    customIcon: "Свой emoji",
    completedToday: "Сегодня выполнено",
    longestStreak: "Самая длинная серия",
    todayPercent: "% за сегодня",
    monthlyView: "Месячный вид",
    newNote: "Новая заметка",
    noteTitle: "Заголовок",
    noteContent: "Текст...",
    general: "Общее",
    business: "Бизнес",
    tech: "Технологии",
    lifeScoreLabel: "Life Score",
    completedLabel: "Выполнено",
    failedLabel: "Не выполнено",
    totalStreak: "Всего серий",
    goalsProgress: "Прогресс целей",
    weeklyTasksChart: "Задачи за неделю",
    monthlyLifeScore: "Месячный Life Score",
    taskStatus: "Статус задач",
    failedTasksWarning: "Невыполненные задачи",
    habitStreaks: "Серии привычек",
    unlockedAchievements: "Открытые достижения",
    medals: "Медали",
    topStreaks: "Топ серий",
    achievedLabel: "Выполнено",
    certificatesTitle: "Сертификаты и достижения",
    certificatesDesc: "Дипломы, награды, результаты",
    certName: "Название",
    certIssuer: "Кто выдал",
    certDesc: "Описание",
    certLink: "Ссылка (необяз.)",
    certFile: "Загрузить файл (фото/PDF)",
    friendsTitle: "Друзья и реферал",
    friendsDesc: "Приглашайте друзей и получайте бонусы",
    invited: "Приглашено",
    pointsEarned: "Получено баллов",
    referralCode: "Реф. код",
    inviteLink: "Ссылка приглашения",
    copy: "Копировать",
    copied: "Скопировано!",
    rewardLevels: "Уровни наград",
    friendsList: "Список друзей",
    noFriendsYet: "Друзья ещё не приглашены",
    inviteFriends: "друзей пригласить",
    reward: "Награда",
    achieved: "Получено",
    premiumTitle: "Премиум",
    premiumDesc: "Используйте Flowly на полную мощность",
    trialBanner: "7-дневный VIP пробный период",
    trialEnds: "Дата окончания",
    allFeaturesOpen: "Все Premium функции вам доступны!",
    referralDiscount: "Скидка за друзей!",
    currentPlan: "Текущий план",
    selectPlan: "Выбрать",
    popular: "Популярный",
    pointsSystem: "Система баллов",
    pointsDesc: "Баллами можно купить Premium план",
    dayActivity: "дн. активности",
    consecutive: "дн. подряд",
    fullWeek: "полная неделя",
    settingsTitle: "Настройки",
    appearance: "Внешний вид",
    darkTheme: "Тёмная тема",
    lightTheme: "Светлая тема",
    languageLabel: "Язык",
    notificationsLabel: "Уведомления",
    pushNotifs: "Push уведомления",
    emailNotifs: "Email уведомления",
    reminders: "Напоминания",
    weeklyReport: "Еженедельный отчёт",
    account: "Аккаунт",
    viewProfile: "Смотреть профиль",
    profileTitle: "Профиль",
    personalInfo: "Личная информация",
    accountInfo: "Данные аккаунта",
    plan: "План",
    memberSince: "Участник с",
    helpTitle: "Помощь и поддержка",
    helpDesc: "Есть вопросы? Мы поможем!",
    faq: "Часто задаваемые вопросы",
    liveChat: "Онлайн чат",
    contactUs: "Связаться с нами",
    telegram: "Telegram",
    phoneSupport: "Телефон",
    locationTitle: "Локация и карта",
    locationDesc: "Геолокация, карта и навигация",
    addPlace: "Добавить место",
    searchPlace: "Поиск места...",
    placeName: "Название места",
    placeAddress: "Адрес",
    openInMaps: "На карте",
    getDirections: "Маршрут",
    eventsLocation: "Места событий",
    adminTitle: "Админ панель",
    adminDesc: "Управление пользователями",
    totalUsers: "Всего пользователей",
    premiumUsers: "Премиум",
    freeUsers: "Бесплатно",
    admins: "Админы",
    searchUser: "Поиск пользователя...",
    noAccess: "Нет доступа",
    adminOnly: "Этот раздел только для админов",
    notifications: "Уведомления",
    clearAll: "Очистить",
    noNotifications: "Нет уведомлений",
    minutesBefore: "минут до",
    taskReminder: "Напоминание о задаче",
  },
  en: {
    welcome: "Welcome",
    login: "Sign In",
    signup: "Sign Up",
    email: "Email or phone",
    password: "Password",
    phone: "Phone number",
    code: "Verification code",
    sendCode: "Send Code",
    verifyCode: "Verify",
    resetPassword: "Reset Password",
    orLoginWith: "Or sign in with",
    google: "Google",
    icloud: "iCloud",
    phoneLogin: "Phone",
    forgotPassword: "Forgot password?",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    name: "First Name",
    surname: "Last Name",
    age: "Age",
    address: "Address",
    createAccount: "Create Account",
    enterCode: "Enter code",
    enterPhone: "Enter phone number",
    requiredFields: "Email and password are required",
    back: "Back",
    slogan: "Plan. Act. Achieve.",
    description: "Manage your life — daily, weekly, monthly, and yearly plans",
    dashboard: "Main",
    dailyPlanner: "Daily",
    weeklyPlanner: "Weekly",
    monthlyPlanner: "Monthly",
    yearlyGoals: "Goals",
    habitTracker: "Habits",
    notes: "Notes",
    analytics: "Analytics",
    achievements: "Achievements",
    location: "Map",
    certificates: "Certificates",
    friends: "Friends",
    premium: "Premium",
    settings: "Settings",
    profile: "Profile",
    help: "Help",
    adminPanel: "Admin Panel",
    crmErp: "CRM / ERP",
    search: "Search...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    close: "Close",
    yes: "Yes",
    no: "No",
    loading: "Loading...",
    noData: "No data",
    today: "Today",
    tomorrow: "Tomorrow",
    yesterday: "Yesterday",
    week: "Week",
    month: "Month",
    year: "Year",
    all: "All",
    completed: "Completed",
    notCompleted: "Not completed",
    progress: "Progress",
    streak: "Streak",
    points: "Points",
    logout: "Log out",
    switchAccount: "Switch account",
    welcomeUser: "Welcome",
    lifeScore: "Life Activity Score",
    todayTasks: "Today's tasks",
    upcomingEvents: "Upcoming events",
    activeStreaks: "Active Streaks",
    aiRecommendations: "AI Recommendations",
    excellent: "Excellent!",
    average: "Average",
    needsImprovement: "Needs improvement",
    dailyTasks: "Daily tasks",
    weeklyTasks: "Weekly tasks",
    maxStreak: "Max Streak",
    newTask: "New task",
    taskName: "Task name",
    time: "Time",
    priority: "Priority",
    high: "High",
    medium: "Medium",
    low: "Low",
    category: "Category",
    personal: "Personal",
    education: "Education",
    health: "Health",
    work: "Work",
    finance: "Finance",
    todayProgress: "Today's progress",
    addTask: "Add task",
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
    noTasks: "No tasks",
    addEvent: "Add event",
    eventName: "Event name",
    eventType: "Type",
    birthday: "Birthday",
    exam: "Exam",
    meeting: "Meeting",
    event: "Event",
    locationLabel: "Location",
    noEventsDay: "No events this day",
    newGoal: "New goal",
    goalName: "Goal name",
    deadline: "Deadline",
    steps: "Steps",
    stepsHint: "Each line — new step",
    overallProgress: "Overall progress",
    newHabit: "New habit",
    habitName: "Habit name",
    dailyTarget: "Daily target",
    selectIcon: "Select icon",
    customIcon: "Custom emoji",
    completedToday: "Completed today",
    longestStreak: "Longest streak",
    todayPercent: "Today %",
    monthlyView: "Monthly view",
    newNote: "New note",
    noteTitle: "Title",
    noteContent: "Content...",
    general: "General",
    business: "Business",
    tech: "Technology",
    lifeScoreLabel: "Life Score",
    completedLabel: "Completed",
    failedLabel: "Failed",
    totalStreak: "Total streaks",
    goalsProgress: "Goals progress",
    weeklyTasksChart: "Weekly tasks",
    monthlyLifeScore: "Monthly Life Score",
    taskStatus: "Task status",
    failedTasksWarning: "Failed tasks",
    habitStreaks: "Habit streaks",
    unlockedAchievements: "Unlocked achievements",
    medals: "Medals",
    topStreaks: "Top Streaks",
    achievedLabel: "Achieved",
    certificatesTitle: "Certificates & Achievements",
    certificatesDesc: "Diplomas, awards, accomplishments",
    certName: "Name",
    certIssuer: "Issuer",
    certDesc: "Description",
    certLink: "Link (optional)",
    certFile: "Upload file (image/PDF)",
    friendsTitle: "Friends & Referral",
    friendsDesc: "Invite friends and earn bonuses",
    invited: "Invited",
    pointsEarned: "Points earned",
    referralCode: "Referral code",
    inviteLink: "Invite link",
    copy: "Copy",
    copied: "Copied!",
    rewardLevels: "Reward levels",
    friendsList: "Friends list",
    noFriendsYet: "No friends invited yet",
    inviteFriends: "friends to invite",
    reward: "Reward",
    achieved: "Earned",
    premiumTitle: "Premium",
    premiumDesc: "Unlock Flowly's full power",
    trialBanner: "7-day VIP trial",
    trialEnds: "Ends on",
    allFeaturesOpen: "All Premium features are unlocked!",
    referralDiscount: "Friends discount!",
    currentPlan: "Current plan",
    selectPlan: "Select",
    popular: "Popular",
    pointsSystem: "Points system",
    pointsDesc: "Use points to purchase Premium plans",
    dayActivity: "day activity",
    consecutive: "consecutive days",
    fullWeek: "full week",
    settingsTitle: "Settings",
    appearance: "Appearance",
    darkTheme: "Dark theme",
    lightTheme: "Light theme",
    languageLabel: "Language",
    notificationsLabel: "Notifications",
    pushNotifs: "Push notifications",
    emailNotifs: "Email notifications",
    reminders: "Reminders",
    weeklyReport: "Weekly report",
    account: "Account",
    viewProfile: "View profile",
    profileTitle: "Profile",
    personalInfo: "Personal information",
    accountInfo: "Account info",
    plan: "Plan",
    memberSince: "Member since",
    helpTitle: "Help & Support",
    helpDesc: "Have questions? We're here to help!",
    faq: "Frequently Asked Questions",
    liveChat: "Live Chat",
    contactUs: "Contact Us",
    telegram: "Telegram",
    phoneSupport: "Phone",
    locationTitle: "Location & Map",
    locationDesc: "Geolocation, map and navigation",
    addPlace: "Add place",
    searchPlace: "Search place...",
    placeName: "Place name",
    placeAddress: "Address",
    openInMaps: "Open in Maps",
    getDirections: "Directions",
    eventsLocation: "Events location",
    adminTitle: "Admin Panel",
    adminDesc: "User management",
    totalUsers: "Total users",
    premiumUsers: "Premium",
    freeUsers: "Free",
    admins: "Admins",
    searchUser: "Search user...",
    noAccess: "Access denied",
    adminOnly: "This section is admin-only",
    notifications: "Notifications",
    clearAll: "Clear all",
    noNotifications: "No notifications",
    minutesBefore: "minutes before",
    taskReminder: "Task reminder",
  }
};

export function AuthProvider({ children }) {
  const [users, setUsers] = useState(() => {
    const saved = localStorage.getItem('flowly-users');
    return saved ? JSON.parse(saved) : defaultUsers;
  });

  const [currentUser, setCurrentUser] = useState(() => {
    const saved = localStorage.getItem('flowly-current-user');
    return saved ? JSON.parse(saved) : null;
  });

  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('flowly-language') || 'uz';
  });

  useEffect(() => { localStorage.setItem('flowly-users', JSON.stringify(users)); }, [users]);
  useEffect(() => { localStorage.setItem('flowly-current-user', JSON.stringify(currentUser)); }, [currentUser]);
  useEffect(() => { localStorage.setItem('flowly-language', language); }, [language]);

  const t = (key) => translations[language]?.[key] || translations['en'][key] || key;

  const login = (emailOrPhone, password) => {
    const user = users.find(u => (u.email === emailOrPhone || u.phone === emailOrPhone || u.login === emailOrPhone) && u.password === password);
    if (user) { setCurrentUser(user); return { success: true }; }
    return { success: false, error: language === 'ru' ? 'Неверные данные' : language === 'en' ? 'Invalid credentials' : 'Noto\'g\'ri ma\'lumotlar' };
  };

  const loginWithGoogle = () => {
    const gUser = users.find(u => u.email === 'admin@flowly.uz') || users[0];
    if (gUser) { setCurrentUser(gUser); return { success: true }; }
    return { success: false };
  };

  const loginWithPhone = (phone, code) => {
    const user = users.find(u => u.phone === phone);
    if (user && code === '1234') { setCurrentUser(user); return { success: true }; }
    return { success: false, error: 'Invalid code' };
  };

  const signup = (userData) => {
    const exists = users.find(u => u.email === userData.email || u.phone === userData.phone);
    if (exists) return { success: false, error: t('haveAccount') };

    const newUser = {
      id: Date.now().toString(),
      email: userData.email,
      phone: userData.phone,
      password: userData.password,
      login: userData.login || userData.email.split('@')[0],
      name: userData.name || '',
      surname: userData.surname || '',
      age: userData.age || '',
      address: userData.address || '',
      avatar: null,
      role: 'user',
      plan: 'free',
      planExpiry: null,
      points: 0,
      trialEndsAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      joinedAt: new Date().toISOString().split('T')[0],
      referralCode: 'FL' + Date.now().toString(36).toUpperCase(),
      referredBy: userData.referralCode || null,
      friends: [],
      language: language,
      loginStreak: 1,
      lastLoginDate: new Date().toISOString().split('T')[0],
      totalLogins: 1,
    };

    setUsers([...users, newUser]);
    setCurrentUser(newUser);
    return { success: true };
  };

  const logout = () => { setCurrentUser(null); };

  const updateProfile = (data) => {
    const updated = { ...currentUser, ...data };
    setCurrentUser(updated);
    setUsers(users.map(u => u.id === updated.id ? updated : u));
  };

  const updateUserByAdmin = (userId, data) => {
    setUsers(users.map(u => u.id === userId ? { ...u, ...data } : u));
  };

  const addPoints = (amount) => {
    if (currentUser) {
      const updated = { ...currentUser, points: currentUser.points + amount };
      setCurrentUser(updated);
      setUsers(users.map(u => u.id === updated.id ? updated : u));
    }
  };

  // Daily bonus check - returns bonus info if applicable
  const checkDailyBonus = () => {
    if (!currentUser) return null;
    const today = new Date().toISOString().split('T')[0];
    if (currentUser.lastLoginDate === today) return null; // already claimed today

    const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
    const isConsecutive = currentUser.lastLoginDate === yesterday;
    const newStreak = isConsecutive ? (currentUser.loginStreak || 0) + 1 : 1;

    // Bonus table: day 1=1, 2=2, 3=5, 4=7, 5=8, 6=12, 7=15
    const bonusTable = [0, 1, 2, 5, 7, 8, 12, 15];
    const dayIndex = Math.min(newStreak, 7);
    const bonus = bonusTable[dayIndex];

    return { streak: newStreak, bonus, dayIndex };
  };

  const claimDailyBonus = () => {
    const bonusInfo = checkDailyBonus();
    if (!bonusInfo || !currentUser) return null;

    const today = new Date().toISOString().split('T')[0];
    const updated = {
      ...currentUser,
      points: currentUser.points + bonusInfo.bonus,
      loginStreak: bonusInfo.streak,
      lastLoginDate: today,
      totalLogins: (currentUser.totalLogins || 0) + 1,
    };
    setCurrentUser(updated);
    setUsers(users.map(u => u.id === updated.id ? updated : u));
    return bonusInfo;
  };

  // Points shop - discount calculation
  const getPointsDiscount = (points) => {
    if (points >= 1000) return 50;
    if (points >= 250) return 10;
    if (points >= 100) return 3;
    if (points >= 50) return 1;
    return 0;
  };

  // Purchase plan with card
  const purchasePlan = (planType, months) => {
    if (!currentUser) return false;
    const expiry = new Date();
    expiry.setMonth(expiry.getMonth() + months);
    const updated = { ...currentUser, plan: planType, planExpiry: expiry.toISOString() };
    setCurrentUser(updated);
    setUsers(users.map(u => u.id === updated.id ? updated : u));
    return true;
  };

  // Spend points for discount
  const spendPoints = (amount) => {
    if (!currentUser || currentUser.points < amount) return false;
    const updated = { ...currentUser, points: currentUser.points - amount };
    setCurrentUser(updated);
    setUsers(users.map(u => u.id === updated.id ? updated : u));
    return true;
  };

  return (
    <AuthContext.Provider value={{
      currentUser, users, language, setLanguage, t,
      login, loginWithGoogle, loginWithPhone, signup, logout,
      updateProfile, updateUserByAdmin, addPoints,
      checkDailyBonus, claimDailyBonus, getPointsDiscount, purchasePlan, spendPoints,
    }}>
      {children}
    </AuthContext.Provider>
  );
}

export const useAuth = () => useContext(AuthContext);
